-- Create a user
CREATE USER $1 WITH PASSWORD $2;

GRANT CONNECT ON DATABASE $3 TO $1;
GRANT USAGE ON SCHEMA $4 TO $1;

GRANT SELECT, INSERT, DELETE ON ALL TABLES IN SCHEMA $4 TO $1;

GRANT USAGE ON SEQUENCE [sequence name] TO [user name];